name: flutter_date_range_picker
description: A Flutter package for all platform which provides a custom date picker
publish_to: 'none'
version: 1.0.2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:

  intl: 

  syncfusion_flutter_datepicker: 

  pattern_formatter: 

  flutter_svg: 

  debounce_throttle: 

  pointer_interceptor: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 

flutter:
  uses-material-design: true

  assets:
    - assets/images/
